"""empty message

Revision ID: 39267fd3b637
Revises: 0769af536314
Create Date: 2021-05-25 00:08:41.364618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39267fd3b637'
down_revision = '0769af536314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notification_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('notification_type_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_swipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('swipe_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_account', sa.Column('lat', sa.Numeric(), nullable=True))
    op.add_column('user_account', sa.Column('long', sa.Numeric(), nullable=True))
    op.add_column('user_preference', sa.Column('distance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preference', 'distance')
    op.drop_column('user_account', 'long')
    op.drop_column('user_account', 'lat')
    op.drop_table('user_swipes')
    op.drop_table('user_notification_feed')
    op.drop_table('notification_type')
    # ### end Alembic commands ###
