"""empty message

Revision ID: 45dacf42e72e
Revises: 1b2f74475b89
Create Date: 2021-04-17 19:08:16.653683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45dacf42e72e'
down_revision = '1b2f74475b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sexual_orientation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('interested_gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_account', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('user_account', sa.Column('birth_date', sa.DateTime(), nullable=True))
    op.add_column('user_account', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user_account', sa.Column('job', sa.String(), nullable=True))
    op.add_column('user_account', sa.Column('modified', sa.DateTime(), nullable=True))
    op.add_column('user_account', sa.Column('preference_id', sa.Integer(), nullable=True))
    op.add_column('user_account', sa.Column('sexual_orientation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_account', 'user_preference', ['preference_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_account', 'sexual_orientation', ['sexual_orientation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='foreignkey')
    op.drop_constraint(None, 'user_account', type_='foreignkey')
    op.drop_column('user_account', 'sexual_orientation_id')
    op.drop_column('user_account', 'preference_id')
    op.drop_column('user_account', 'modified')
    op.drop_column('user_account', 'job')
    op.drop_column('user_account', 'created')
    op.drop_column('user_account', 'birth_date')
    op.drop_column('user_account', 'bio')
    op.drop_table('user_preference')
    op.drop_table('sexual_orientation')
    # ### end Alembic commands ###
