"""empty message

Revision ID: 57402fafcd49
Revises: 86f7f375efb6
Create Date: 2021-05-11 23:35:25.975823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57402fafcd49'
down_revision = '86f7f375efb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('preference_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_account', 'user_preference', ['preference_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='foreignkey')
    op.drop_column('user_account', 'preference_id')
    # ### end Alembic commands ###
