"""empty message

Revision ID: ad13622732ab
Revises: 
Create Date: 2021-03-27 00:02:35.734041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad13622732ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
