"""empty message

Revision ID: ae0b38a2db55
Revises: ad13622732ab
Create Date: 2021-03-27 00:05:06.937431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0b38a2db55'
down_revision = 'ad13622732ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('password', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'password')
    # ### end Alembic commands ###
