"""empty message

Revision ID: c86f98206569
Revises: 0688c6bff36b
Create Date: 2021-06-08 23:10:17.505388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86f98206569'
down_revision = '0688c6bff36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notification_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('to_user_id', sa.String(length=256), nullable=True),
    sa.Column('notification_type_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user_account.public_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_type_id'], ['notification_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['user_account.public_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user_account', 'public_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'public_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_table('user_notification_feed')
    # ### end Alembic commands ###
