"""empty message

Revision ID: 979a756c6144
Revises: 38874c89a776
Create Date: 2021-05-07 23:14:52.819571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979a756c6144'
down_revision = '38874c89a776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('preference_id', sa.Integer(), nullable=True))
    op.add_column('user_account', sa.Column('sexual_orientation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_account', 'user_preference', ['preference_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'user_account', 'sexual_orientation', ['sexual_orientation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='foreignkey')
    op.drop_constraint(None, 'user_account', type_='foreignkey')
    op.drop_column('user_account', 'sexual_orientation_id')
    op.drop_column('user_account', 'preference_id')
    # ### end Alembic commands ###
